# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: "CI: checks and tests"

on:
  push:
    branches: ["develop", "main", "feature/*", "bugfix/*", "hotfix/*"]
  pull_request:
    branches: ["develop", "main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@4606d5cc6fb3f673efd4f594850e3f4b3e9d29cd
        with:
          deno-version: v2.x

      - name: Run linter
        run: deno task lint

      - name: Run tests
        run: deno task test
