autophoto:
  scan:
    - directory: ./test/resources/video-game
      type: video-game
      data-pattern:
        regex: '^(.+) \(\d{4}\)/(.+)/.+\.webp$'
        groups:
          - name
          - year
          - platform
