name: "CI: build native binaries"

on:
  push:
    branches:
      - main
      - bugfix/**
      - hotfix/**
      - release/**

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      # https://github.com/denoland/setup-deno/releases
      - name: Setup Deno
        uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755
        with:
          deno-version: v2.x

      - name: Build Linux binary ARM
        run: deno task build:linux-arm

      - name: Archive Linux binary ARM
        uses: actions/upload-artifact@v4
        with:
          name: autophoto-linux-arm-2.5.0
          path: build/linux-arm
