name: "CI: checks and tests"

on:
  push:
    branches:
      - develop
      - main
      - feature/**
      - bugfix/**
      - hotfix/**

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@4606d5cc6fb3f673efd4f594850e3f4b3e9d29cd
        with:
          deno-version: v2.x

      - name: Run linter
        run: deno task lint

      - name: Run tests and activate coverage
        run: deno test --allow-read --allow-write --unstable-kv --allow-env --allow-net --coverage -- config.yml --database=./test/it-database.sqlite3 --scan

      - name: Generate lcov report
        run: deno coverage --lcov --output=cov.lcov

      - name: Check test coverage
        uses: terencetcf/github-actions-lcov-minimum-coverage-checker@v1
        with:
          coverage-file: cov.lcov
          minimum-coverage: 90
